# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170512_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
